#!/bin/bash
# Bundle every source file into one self-contained installer.
#
#   ./build.sh   ->   dist/install-jira-watch.sh
#
# The repo is private, so `curl | bash` needs a token nobody wants to hand out.
# A single file can just be sent over Slack instead.
#
# Regenerate this after touching any source file — the bundle is a copy, and a
# stale copy is worse than no copy.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/dist/install-jira-watch.sh"
SOURCES=(watch.mjs act.mjs env.mjs jira.mjs JiraNotify.applescript uninstall.sh)

mkdir -p "$HERE/dist"

# A delimiter that cannot appear in the sources. Checked below rather than hoped.
DELIM="__JIRA_WATCH_FILE_BOUNDARY__"
for f in "${SOURCES[@]}" install.sh; do
  if grep -qF "$DELIM" "$HERE/$f"; then
    echo "Delimiter collides with content of $f — pick another one." >&2
    exit 1
  fi
done

{
  cat <<'HEADER'
#!/bin/bash
# Jira watcher — self-contained installer. No git clone needed.
#
#   bash install-jira-watch.sh              # installs into ~/Projects/jira-watch
#   TARGET=~/tools/jira-watch bash install-jira-watch.sh
#   INTERVAL=15 bash install-jira-watch.sh  # faster polling
#
# Generated by build.sh — do not edit by hand, edit the sources and rebuild.

set -euo pipefail

TARGET="${TARGET:-$HOME/Projects/jira-watch}"
mkdir -p "$TARGET"
HERE="$TARGET"

echo "Giải nén vào $TARGET"
HEADER

  for f in "${SOURCES[@]}"; do
    printf "cat > \"\$TARGET/%s\" <<'%s'\n" "$f" "$DELIM"
    cat "$HERE/$f"
    printf "%s\n\n" "$DELIM"
  done

  cat <<'MIDDLE'
chmod +x "$TARGET/uninstall.sh"

# Lets the build be verified without installing anything.
if [ -n "${EXTRACT_ONLY:-}" ]; then
  echo "EXTRACT_ONLY — dừng sau khi giải nén."
  exit 0
fi

MIDDLE

  # install.sh minus its shebang, its own `set`, and the HERE it computes from
  # $0 — here HERE is the extraction target instead.
  sed -e '1d' \
      -e '/^set -euo pipefail$/d' \
      -e '/^HERE="\$(cd "\$(dirname "\${BASH_SOURCE\[0\]}")" && pwd)"$/d' \
      "$HERE/install.sh"
} > "$OUT"

chmod +x "$OUT"

LINES=$(wc -l < "$OUT" | tr -d ' ')
SIZE=$(du -h "$OUT" | cut -f1 | tr -d ' ')
bash -n "$OUT" || { echo "Bundle không hợp lệ về cú pháp." >&2; exit 1; }

echo "✓ $OUT  ($LINES dòng, $SIZE)"
